# Generated by Django 4.1.2 on 2022-11-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0002_rename_perfume_perfumeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumeinfo',
            name='price',
        ),
        migrations.CreateModel(
            name='MenPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('size', models.FloatField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='perfume_shop.perfumeinfo')),
            ],
        ),
    ]
