# Generated by Django 4.1.2 on 2022-11-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0003_remove_perfumeinfo_price_menperfume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('size', models.FloatField()),
                ('sex', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='MenPerfume',
        ),
        migrations.DeleteModel(
            name='PerfumeInfo',
        ),
    ]
