# Generated by Django 4.1.2 on 2022-11-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0005_tester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfume',
            new_name='PerfumeInfo',
        ),
    ]
