# Generated by Django 4.1.2 on 2022-11-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0006_rename_perfume_perfumeinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerfumeInfo',
            new_name='Perfume',
        ),
    ]
