# Generated by Django 4.1.2 on 2022-11-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0007_rename_perfumeinfo_perfume'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('size', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('tester', models.BooleanField(default=False)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume_shop.perfume')),
            ],
        ),
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
