# Generated by Django 4.1.2 on 2022-11-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0009_brand_perfume_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='brand',
        ),
    ]
