# Generated by Django 4.1.2 on 2022-11-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0010_remove_perfume_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
