# Generated by Django 4.1.2 on 2022-11-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0013_perfume_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='sex',
            field=models.CharField(max_length=3),
        ),
    ]
