# Generated by Django 4.1.2 on 2022-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0014_alter_brand_category_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.CharField(choices=[('LUX', 'LUX'), ('Designer', 'Designer')], max_length=20),
        ),
    ]
