# Generated by Django 4.1.2 on 2022-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0016_remove_perfume_sex_perfume_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='price',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='size',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
