# Generated by Django 4.1.2 on 2022-11-07 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0018_cart_cartproduct_cart_products_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumebottle',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
