# Generated by Django 4.1.2 on 2022-11-07 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0020_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
