# Generated by Django 4.1.2 on 2022-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0021_alter_rating_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumebottle',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
