# Generated by Django 4.1.2 on 2022-11-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0022_perfumebottle_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumebottle',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
