# Generated by Django 4.1.2 on 2022-11-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0023_alter_perfumebottle_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='perfume',
        ),
    ]
