# Generated by Django 4.1.2 on 2022-11-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0024_rename_product_rating_perfume'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(default='p1.png', upload_to='perfumes'),
        ),
    ]
