# Generated by Django 4.1.2 on 2022-11-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0028_perfume_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='image',
        ),
    ]
