# Generated by Django 4.1.2 on 2022-11-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0030_perfume_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='brands/p1.jpg', upload_to='brands'),
        ),
    ]
