# Generated by Django 4.1.2 on 2022-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0034_remove_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='brands/aramis.png', upload_to='brands'),
        ),
    ]
