# Generated by Django 4.1.2 on 2022-11-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0035_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumebottle',
            name='rate',
        ),
        migrations.AddField(
            model_name='perfumebottle',
            name='discount',
            field=models.IntegerField(default=10),
        ),
    ]
