# Generated by Django 4.1.2 on 2022-11-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0037_perfumebottle_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfumebottle',
            name='rate',
        ),
    ]
