# Generated by Django 4.1.2 on 2022-11-09 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0040_remove_perfumebottle_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumebottle',
            name='discount',
            field=models.PositiveIntegerField(default=817),
        ),
        migrations.AddField(
            model_name='perfumebottle',
            name='price',
            field=models.FloatField(default=27484680.4, validators=[django.core.validators.MinValueValidator(1000000)]),
        ),
        migrations.AddField(
            model_name='perfumebottle',
            name='quantity',
            field=models.PositiveIntegerField(default=829),
        ),
        migrations.AddField(
            model_name='perfumebottle',
            name='size',
            field=models.FloatField(default=628.13, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='rate',
            field=models.FloatField(default=3.74, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
