# Generated by Django 4.1.2 on 2022-11-17 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0062_alter_perfumebottle_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumebottle',
            name='discount',
            field=models.PositiveIntegerField(default=29),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='price',
            field=models.FloatField(default=3510641.34, validators=[django.core.validators.MinValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='quantity',
            field=models.PositiveIntegerField(default=900),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='rate',
            field=models.FloatField(default=2.58, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='size',
            field=models.FloatField(default=640.05, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.CreateModel(
            name='PaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Sent', 'Send'), ('Received', 'Received')], max_length=30)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume_shop.paymentstrackid')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume_shop.perfumebottle')),
            ],
        ),
    ]
