# Generated by Django 4.1.2 on 2022-11-24 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0067_perfumebottle_name_alter_perfumebottle_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='dispersal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfume',
            name='nature',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfume',
            name='olfaction_group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfume_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfume',
            name='persistence',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfume',
            name='season',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfumebottle',
            name='perfumer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='discount',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='price',
            field=models.FloatField(default=28065668.67, validators=[django.core.validators.MinValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='quantity',
            field=models.PositiveIntegerField(default=490),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='rate',
            field=models.FloatField(default=3.21, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='size',
            field=models.FloatField(default=188.85, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
