# Generated by Django 4.1.2 on 2022-11-27 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume_shop', '0074_alter_paymentstrackid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstrackid',
            name='shipping_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perfume_shop.address'),
        ),
        migrations.AlterField(
            model_name='paymentstrackid',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Processing', 'Processing'), ('Sent', 'Send'), ('Received', 'Received')], max_length=30),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='discount',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='price',
            field=models.FloatField(default=14438128.04, validators=[django.core.validators.MinValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='quantity',
            field=models.PositiveIntegerField(default=611),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='rate',
            field=models.FloatField(default=0.21, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='perfumebottle',
            name='size',
            field=models.FloatField(default=612.55, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
